/* tslint:disable */

/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AccountProvider
 */
export interface AccountProvider {
  /**
   *
   * @type {string}
   * @memberof AccountProvider
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof AccountProvider
   */
  displayName: string
}
