/* tslint:disable */

/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrganizationUsageOverview
 */
export interface OrganizationUsageOverview {
  /**
   *
   * @type {number}
   * @memberof OrganizationUsageOverview
   */
  totalCpuQuota: number
  /**
   *
   * @type {number}
   * @memberof OrganizationUsageOverview
   */
  totalMemoryQuota: number
  /**
   *
   * @type {number}
   * @memberof OrganizationUsageOverview
   */
  totalDiskQuota: number
  /**
   *
   * @type {number}
   * @memberof OrganizationUsageOverview
   */
  currentCpuUsage: number
  /**
   *
   * @type {number}
   * @memberof OrganizationUsageOverview
   */
  currentMemoryUsage: number
  /**
   *
   * @type {number}
   * @memberof OrganizationUsageOverview
   */
  currentDiskUsage: number
  /**
   *
   * @type {number}
   * @memberof OrganizationUsageOverview
   */
  totalSnapshotQuota: number
  /**
   *
   * @type {number}
   * @memberof OrganizationUsageOverview
   */
  currentSnapshotUsage: number
  /**
   *
   * @type {number}
   * @memberof OrganizationUsageOverview
   */
  totalVolumeQuota: number
  /**
   *
   * @type {number}
   * @memberof OrganizationUsageOverview
   */
  currentVolumeUsage: number
}
