/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegionQuota
 */
export interface RegionQuota {
    /**
     * 
     * @type {string}
     * @memberof RegionQuota
     */
    'organizationId': string;
    /**
     * 
     * @type {string}
     * @memberof RegionQuota
     */
    'regionId': string;
    /**
     * 
     * @type {number}
     * @memberof RegionQuota
     */
    'totalCpuQuota': number;
    /**
     * 
     * @type {number}
     * @memberof RegionQuota
     */
    'totalMemoryQuota': number;
    /**
     * 
     * @type {number}
     * @memberof RegionQuota
     */
    'totalDiskQuota': number;
}

