/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The class of the runner
 */

export const RunnerClass = {
    CONTAINER: 'container',
    VM: 'vm',
} as const;

export type RunnerClass = typeof RunnerClass[keyof typeof RunnerClass];



