/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SandboxVolume
 */
export interface SandboxVolume {
    /**
     * The ID of the volume
     * @type {string}
     * @memberof SandboxVolume
     */
    'volumeId': string;
    /**
     * The mount path for the volume
     * @type {string}
     * @memberof SandboxVolume
     */
    'mountPath': string;
    /**
     * Optional subpath within the volume to mount. When specified, only this S3 prefix will be accessible. When omitted, the entire volume is mounted.
     * @type {string}
     * @memberof SandboxVolume
     */
    'subpath'?: string;
}

