/* tslint:disable */

/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SandboxStateUpdatedPostRequestDataSandbox
 */
export interface SandboxStateUpdatedPostRequestDataSandbox {
  /**
   *
   * @type {string}
   * @memberof SandboxStateUpdatedPostRequestDataSandbox
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof SandboxStateUpdatedPostRequestDataSandbox
   */
  organizationId?: string
  /**
   *
   * @type {string}
   * @memberof SandboxStateUpdatedPostRequestDataSandbox
   */
  state?: SandboxStateUpdatedPostRequestDataSandboxStateEnum
}

export const SandboxStateUpdatedPostRequestDataSandboxStateEnum = {
  CREATING: 'creating',
  RESTORING: 'restoring',
  DESTROYED: 'destroyed',
  DESTROYING: 'destroying',
  STARTED: 'started',
  STOPPED: 'stopped',
  STARTING: 'starting',
  STOPPING: 'stopping',
  ERROR: 'error',
  BUILD_FAILED: 'build_failed',
  PENDING_BUILD: 'pending_build',
  BUILDING_SNAPSHOT: 'building_snapshot',
  UNKNOWN: 'unknown',
  PULLING_SNAPSHOT: 'pulling_snapshot',
  ARCHIVED: 'archived',
  ARCHIVING: 'archiving',
} as const

export type SandboxStateUpdatedPostRequestDataSandboxStateEnum =
  (typeof SandboxStateUpdatedPostRequestDataSandboxStateEnum)[keyof typeof SandboxStateUpdatedPostRequestDataSandboxStateEnum]
