/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SnapshotNotFoundError {
    'statusCode': number;
    'source': string;
    'code': SnapshotNotFoundErrorCodeEnum;
    'message': string;
    'timestamp': string;
    'path': string;
    'method': string;
}

export const SnapshotNotFoundErrorCodeEnum = {
    SNAPSHOT_NOT_FOUND: 'SNAPSHOT_NOT_FOUND',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type SnapshotNotFoundErrorCodeEnum = typeof SnapshotNotFoundErrorCodeEnum[keyof typeof SnapshotNotFoundErrorCodeEnum];


