/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BuildInfo } from './build-info';
// May contain unused imports in some cases
// @ts-ignore
import type { GpuType } from './gpu-type';
// May contain unused imports in some cases
// @ts-ignore
import type { SnapshotState } from './snapshot-state';

export interface SnapshotDto {
    'id': string;
    'organizationId'?: string;
    'general': boolean;
    'name': string;
    'imageName'?: string;
    'state': SnapshotState;
    'size': number | null;
    'entrypoint': Array<string> | null;
    'cpu': number;
    'gpu': number;
    /**
     * The GPU type assigned to the snapshot
     */
    'gpuType'?: GpuType;
    'mem': number;
    'disk': number;
    'errorReason': string | null;
    'createdAt': Date;
    'updatedAt': Date;
    'lastUsedAt': Date | null;
    /**
     * Build information for the snapshot
     */
    'buildInfo'?: BuildInfo;
    /**
     * IDs of regions where the snapshot is available
     */
    'regionIds'?: Array<string>;
    /**
     * The initial runner ID of the snapshot
     */
    'initialRunnerId'?: string;
    /**
     * The snapshot reference
     */
    'ref'?: string;
    /**
     * The sandbox class of the snapshot
     */
    'sandboxClass'?: SnapshotDtoSandboxClassEnum;
}

export const SnapshotDtoSandboxClassEnum = {
    LINUX_VM: 'linux-vm',
    CONTAINER: 'container',
    ANDROID: 'android',
    WINDOWS: 'windows',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type SnapshotDtoSandboxClassEnum = typeof SnapshotDtoSandboxClassEnum[keyof typeof SnapshotDtoSandboxClassEnum];


