/* tslint:disable */

/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateAssignedOrganizationRoles
 */
export interface UpdateAssignedOrganizationRoles {
  /**
   * Array of role IDs
   * @type {Array<string>}
   * @memberof UpdateAssignedOrganizationRoles
   */
  roleIds: Array<string>
}
