/* tslint:disable */

/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateOrganizationInvitation
 */
export interface UpdateOrganizationInvitation {
  /**
   * Organization member role
   * @type {string}
   * @memberof UpdateOrganizationInvitation
   */
  role: UpdateOrganizationInvitationRoleEnum
  /**
   * Array of role IDs
   * @type {Array<string>}
   * @memberof UpdateOrganizationInvitation
   */
  assignedRoleIds: Array<string>
  /**
   * Expiration date of the invitation
   * @type {Date}
   * @memberof UpdateOrganizationInvitation
   */
  expiresAt?: Date
}

export const UpdateOrganizationInvitationRoleEnum = {
  OWNER: 'owner',
  MEMBER: 'member',
} as const

export type UpdateOrganizationInvitationRoleEnum =
  (typeof UpdateOrganizationInvitationRoleEnum)[keyof typeof UpdateOrganizationInvitationRoleEnum]
