/*
 * Copyright 2025 Daytona Platforms Inc.
 * SPDX-License-Identifier: AGPL-3.0
 */

export enum JobType {
  CREATE_SANDBOX = 'CREATE_SANDBOX',
  START_SANDBOX = 'START_SANDBOX',
  STOP_SANDBOX = 'STOP_SANDBOX',
  DESTROY_SANDBOX = 'DESTROY_SANDBOX',
  RESIZE_SANDBOX = 'RESIZE_SANDBOX',
  CREATE_BACKUP = 'CREATE_BACKUP',
  BUILD_SNAPSHOT = 'BUILD_SNAPSHOT',
  PULL_SNAPSHOT = 'PULL_SNAPSHOT',
  RECOVER_SANDBOX = 'RECOVER_SANDBOX',
  INSPECT_SNAPSHOT_IN_REGISTRY = 'INSPECT_SNAPSHOT_IN_REGISTRY',
  REMOVE_SNAPSHOT = 'REMOVE_SNAPSHOT',
  UPDATE_SANDBOX_NETWORK_SETTINGS = 'UPDATE_SANDBOX_NETWORK_SETTINGS',
  CREATE_CHECKPOINT = 'CREATE_CHECKPOINT',
  REMOVE_CHECKPOINT = 'REMOVE_CHECKPOINT',
  GET_CHECKPOINT_INFO = 'GET_CHECKPOINT_INFO',
  INSPECT_CHECKPOINT_IN_REGISTRY = 'INSPECT_CHECKPOINT_IN_REGISTRY',
}
