/*
 * Daytona Analytics API
 * Daytona Analytics API - Read-only telemetry and usage data. Authenticated via Daytona API keys or JWT tokens.
 *
 * The version of the OpenAPI document: v0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.analytics.api.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ModelsUsageChartPoint
 */
public class ModelsUsageChartPointTest {
    private final ModelsUsageChartPoint model = new ModelsUsageChartPoint();

    /**
     * Model tests for ModelsUsageChartPoint
     */
    @Test
    public void testModelsUsageChartPoint() {
        // TODO: test ModelsUsageChartPoint
    }

    /**
     * Test the property 'cpu'
     */
    @Test
    public void cpuTest() {
        // TODO: test cpu
    }

    /**
     * Test the property 'cpuPrice'
     */
    @Test
    public void cpuPriceTest() {
        // TODO: test cpuPrice
    }

    /**
     * Test the property 'diskGB'
     */
    @Test
    public void diskGBTest() {
        // TODO: test diskGB
    }

    /**
     * Test the property 'diskPrice'
     */
    @Test
    public void diskPriceTest() {
        // TODO: test diskPrice
    }

    /**
     * Test the property 'ramGB'
     */
    @Test
    public void ramGBTest() {
        // TODO: test ramGB
    }

    /**
     * Test the property 'ramPrice'
     */
    @Test
    public void ramPriceTest() {
        // TODO: test ramPrice
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

}
