linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/gin-gonic/gin.Context).AbortWithError
      - (*github.com/gin-gonic/gin.Context).Error
      - io.Copy
      - syscall.Syscall
      - (github.com/gliderlabs/ssh.Session).Exit
      - (io.Writer).Write
run:
  build-tags:
    - testing
