header:
  license:
    spdx-id: AGPL-3.0
    copyright-owner: Daytona Platforms Inc.
    content: |
      Copyright Daytona Platforms Inc.
      SPDX-License-Identifier: AGPL-3.0
    pattern: |
      Copyright (\d{4} )?Daytona Platforms Inc\.
      SPDX-License-Identifier: AGPL-3\.0
  paths:
    - '**/*.go'
    - '**/*.sh'
    - '**/*.js'
    - '**/*.ts'
    - '**/*.tsx'
    - '**/*.py'

  paths-ignore:
    - 'libs/**'
    - '!libs/computer-use/**'
    - '!libs/common-go/**'
    - 'apps/api/src/generate-openapi.ts'
    - 'apps/runner/pkg/api/docs/docs.go'
    - 'examples/**'
    - 'apps/docs/**'
    - 'hack/**'
    - 'guides/**'
    - 'apps/daemon/pkg/toolbox/docs/docs.go'
    - 'apps/dashboard/public/mockServiceWorker.js'

  comment: on-failure
