header:
  license:
    spdx-id: AGPL-3.0
    copyright-owner: Daytona Platforms Inc.
    content: |
      Copyright 2025 Daytona Platforms Inc.
      SPDX-License-Identifier: AGPL-3.0
  paths:
    - '**/*.go'
    - '**/*.sh'
    - '**/*.js'
    - '**/*.ts'
    - '**/*.tsx'
    - '**/*.py'

  paths-ignore:
    - 'libs/api-client/**'
    - 'libs/runner-api-client/**'
    - 'libs/api-client-go/**'
    - 'libs/api-client-python/**'
    - 'apps/api/src/generate-openapi.ts'
    - 'apps/runner/pkg/api/docs/docs.go'
    - 'examples/**'

  comment: on-failure
