header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Daytona Platforms Inc.
    content: |
      Copyright 2025 Daytona Platforms Inc.
      SPDX-License-Identifier: Apache-2.0
  paths:
    - 'libs/**/*.go'
    - 'libs/**/*.sh'
    - 'libs/**/*.js'
    - 'libs/**/*.ts'
    - 'libs/**/*.tsx'
    - 'libs/**/*.py'

  paths-ignore:
    - 'libs/api-client/**'
    - 'libs/runner-api-client/**'
    - 'libs/api-client-go/**'
    - 'libs/api-client-python/**'
    - 'libs/api-client-python-async/**'
    - 'apps/docs/**'
    - 'libs/computer-use/**'
    - 'hack/**'

  comment: on-failure
