/*
Daytona Server API

Daytona Server API

API version: v0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WorkspaceViewDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspaceViewDTO{}

// WorkspaceViewDTO struct for WorkspaceViewDTO
type WorkspaceViewDTO struct {
	BuildConfig         *BuildConfig      `json:"buildConfig,omitempty"`
	EnvVars             map[string]string `json:"envVars"`
	GitProviderConfigId *string           `json:"gitProviderConfigId,omitempty"`
	Id                  string            `json:"id"`
	Image               string            `json:"image"`
	Name                string            `json:"name"`
	Repository          GitRepository     `json:"repository"`
	State               *WorkspaceState   `json:"state,omitempty"`
	TargetId            string            `json:"targetId"`
	TargetName          string            `json:"targetName"`
	User                string            `json:"user"`
}

type _WorkspaceViewDTO WorkspaceViewDTO

// NewWorkspaceViewDTO instantiates a new WorkspaceViewDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceViewDTO(envVars map[string]string, id string, image string, name string, repository GitRepository, targetId string, targetName string, user string) *WorkspaceViewDTO {
	this := WorkspaceViewDTO{}
	this.EnvVars = envVars
	this.Id = id
	this.Image = image
	this.Name = name
	this.Repository = repository
	this.TargetId = targetId
	this.TargetName = targetName
	this.User = user
	return &this
}

// NewWorkspaceViewDTOWithDefaults instantiates a new WorkspaceViewDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceViewDTOWithDefaults() *WorkspaceViewDTO {
	this := WorkspaceViewDTO{}
	return &this
}

// GetBuildConfig returns the BuildConfig field value if set, zero value otherwise.
func (o *WorkspaceViewDTO) GetBuildConfig() BuildConfig {
	if o == nil || IsNil(o.BuildConfig) {
		var ret BuildConfig
		return ret
	}
	return *o.BuildConfig
}

// GetBuildConfigOk returns a tuple with the BuildConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceViewDTO) GetBuildConfigOk() (*BuildConfig, bool) {
	if o == nil || IsNil(o.BuildConfig) {
		return nil, false
	}
	return o.BuildConfig, true
}

// HasBuildConfig returns a boolean if a field has been set.
func (o *WorkspaceViewDTO) HasBuildConfig() bool {
	if o != nil && !IsNil(o.BuildConfig) {
		return true
	}

	return false
}

// SetBuildConfig gets a reference to the given BuildConfig and assigns it to the BuildConfig field.
func (o *WorkspaceViewDTO) SetBuildConfig(v BuildConfig) {
	o.BuildConfig = &v
}

// GetEnvVars returns the EnvVars field value
func (o *WorkspaceViewDTO) GetEnvVars() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.EnvVars
}

// GetEnvVarsOk returns a tuple with the EnvVars field value
// and a boolean to check if the value has been set.
func (o *WorkspaceViewDTO) GetEnvVarsOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvVars, true
}

// SetEnvVars sets field value
func (o *WorkspaceViewDTO) SetEnvVars(v map[string]string) {
	o.EnvVars = v
}

// GetGitProviderConfigId returns the GitProviderConfigId field value if set, zero value otherwise.
func (o *WorkspaceViewDTO) GetGitProviderConfigId() string {
	if o == nil || IsNil(o.GitProviderConfigId) {
		var ret string
		return ret
	}
	return *o.GitProviderConfigId
}

// GetGitProviderConfigIdOk returns a tuple with the GitProviderConfigId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceViewDTO) GetGitProviderConfigIdOk() (*string, bool) {
	if o == nil || IsNil(o.GitProviderConfigId) {
		return nil, false
	}
	return o.GitProviderConfigId, true
}

// HasGitProviderConfigId returns a boolean if a field has been set.
func (o *WorkspaceViewDTO) HasGitProviderConfigId() bool {
	if o != nil && !IsNil(o.GitProviderConfigId) {
		return true
	}

	return false
}

// SetGitProviderConfigId gets a reference to the given string and assigns it to the GitProviderConfigId field.
func (o *WorkspaceViewDTO) SetGitProviderConfigId(v string) {
	o.GitProviderConfigId = &v
}

// GetId returns the Id field value
func (o *WorkspaceViewDTO) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WorkspaceViewDTO) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WorkspaceViewDTO) SetId(v string) {
	o.Id = v
}

// GetImage returns the Image field value
func (o *WorkspaceViewDTO) GetImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *WorkspaceViewDTO) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *WorkspaceViewDTO) SetImage(v string) {
	o.Image = v
}

// GetName returns the Name field value
func (o *WorkspaceViewDTO) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WorkspaceViewDTO) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WorkspaceViewDTO) SetName(v string) {
	o.Name = v
}

// GetRepository returns the Repository field value
func (o *WorkspaceViewDTO) GetRepository() GitRepository {
	if o == nil {
		var ret GitRepository
		return ret
	}

	return o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value
// and a boolean to check if the value has been set.
func (o *WorkspaceViewDTO) GetRepositoryOk() (*GitRepository, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Repository, true
}

// SetRepository sets field value
func (o *WorkspaceViewDTO) SetRepository(v GitRepository) {
	o.Repository = v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *WorkspaceViewDTO) GetState() WorkspaceState {
	if o == nil || IsNil(o.State) {
		var ret WorkspaceState
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceViewDTO) GetStateOk() (*WorkspaceState, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *WorkspaceViewDTO) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given WorkspaceState and assigns it to the State field.
func (o *WorkspaceViewDTO) SetState(v WorkspaceState) {
	o.State = &v
}

// GetTargetId returns the TargetId field value
func (o *WorkspaceViewDTO) GetTargetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetId
}

// GetTargetIdOk returns a tuple with the TargetId field value
// and a boolean to check if the value has been set.
func (o *WorkspaceViewDTO) GetTargetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetId, true
}

// SetTargetId sets field value
func (o *WorkspaceViewDTO) SetTargetId(v string) {
	o.TargetId = v
}

// GetTargetName returns the TargetName field value
func (o *WorkspaceViewDTO) GetTargetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetName
}

// GetTargetNameOk returns a tuple with the TargetName field value
// and a boolean to check if the value has been set.
func (o *WorkspaceViewDTO) GetTargetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetName, true
}

// SetTargetName sets field value
func (o *WorkspaceViewDTO) SetTargetName(v string) {
	o.TargetName = v
}

// GetUser returns the User field value
func (o *WorkspaceViewDTO) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *WorkspaceViewDTO) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *WorkspaceViewDTO) SetUser(v string) {
	o.User = v
}

func (o WorkspaceViewDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspaceViewDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BuildConfig) {
		toSerialize["buildConfig"] = o.BuildConfig
	}
	toSerialize["envVars"] = o.EnvVars
	if !IsNil(o.GitProviderConfigId) {
		toSerialize["gitProviderConfigId"] = o.GitProviderConfigId
	}
	toSerialize["id"] = o.Id
	toSerialize["image"] = o.Image
	toSerialize["name"] = o.Name
	toSerialize["repository"] = o.Repository
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	toSerialize["targetId"] = o.TargetId
	toSerialize["targetName"] = o.TargetName
	toSerialize["user"] = o.User
	return toSerialize, nil
}

func (o *WorkspaceViewDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"envVars",
		"id",
		"image",
		"name",
		"repository",
		"targetId",
		"targetName",
		"user",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkspaceViewDTO := _WorkspaceViewDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkspaceViewDTO)

	if err != nil {
		return err
	}

	*o = WorkspaceViewDTO(varWorkspaceViewDTO)

	return err
}

type NullableWorkspaceViewDTO struct {
	value *WorkspaceViewDTO
	isSet bool
}

func (v NullableWorkspaceViewDTO) Get() *WorkspaceViewDTO {
	return v.value
}

func (v *NullableWorkspaceViewDTO) Set(val *WorkspaceViewDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceViewDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceViewDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceViewDTO(val *WorkspaceViewDTO) *NullableWorkspaceViewDTO {
	return &NullableWorkspaceViewDTO{value: val, isSet: true}
}

func (v NullableWorkspaceViewDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceViewDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
