/*
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.api.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets GpuType
 */
@JsonAdapter(GpuType.Adapter.class)
public enum GpuType {
  
  H100("H100"),
  
  RTX_PRO_6000("RTX-PRO-6000"),
  
  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  GpuType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static GpuType fromValue(String value) {
    for (GpuType b : GpuType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<GpuType> {
    @Override
    public void write(final JsonWriter jsonWriter, final GpuType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public GpuType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return GpuType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    GpuType.fromValue(value);
  }
}

