/*
 * Daytona Analytics API
 * Daytona Analytics API - Read-only telemetry and usage data. Authenticated via Daytona API keys or JWT tokens.
 *
 * The version of the OpenAPI document: v0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.analytics.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.daytona.analytics.api.client.JSON;

/**
 * ModelsAggregatedUsage
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ModelsAggregatedUsage {
  public static final String SERIALIZED_NAME_FIRST_START = "firstStart";
  @SerializedName(SERIALIZED_NAME_FIRST_START)
  @javax.annotation.Nullable
  private String firstStart;

  public static final String SERIALIZED_NAME_LAST_END = "lastEnd";
  @SerializedName(SERIALIZED_NAME_LAST_END)
  @javax.annotation.Nullable
  private String lastEnd;

  public static final String SERIALIZED_NAME_SANDBOX_COUNT = "sandboxCount";
  @SerializedName(SERIALIZED_NAME_SANDBOX_COUNT)
  @javax.annotation.Nullable
  private Integer sandboxCount;

  public static final String SERIALIZED_NAME_TOTAL_C_P_U_SECONDS = "totalCPUSeconds";
  @SerializedName(SERIALIZED_NAME_TOTAL_C_P_U_SECONDS)
  @javax.annotation.Nullable
  private Integer totalCPUSeconds;

  public static final String SERIALIZED_NAME_TOTAL_DISK_G_B_SECONDS = "totalDiskGBSeconds";
  @SerializedName(SERIALIZED_NAME_TOTAL_DISK_G_B_SECONDS)
  @javax.annotation.Nullable
  private Integer totalDiskGBSeconds;

  public static final String SERIALIZED_NAME_TOTAL_G_P_U_SECONDS = "totalGPUSeconds";
  @SerializedName(SERIALIZED_NAME_TOTAL_G_P_U_SECONDS)
  @javax.annotation.Nullable
  private Integer totalGPUSeconds;

  public static final String SERIALIZED_NAME_TOTAL_PRICE = "totalPrice";
  @SerializedName(SERIALIZED_NAME_TOTAL_PRICE)
  @javax.annotation.Nullable
  private BigDecimal totalPrice;

  public static final String SERIALIZED_NAME_TOTAL_R_A_M_G_B_SECONDS = "totalRAMGBSeconds";
  @SerializedName(SERIALIZED_NAME_TOTAL_R_A_M_G_B_SECONDS)
  @javax.annotation.Nullable
  private Integer totalRAMGBSeconds;

  public ModelsAggregatedUsage() {
  }

  public ModelsAggregatedUsage firstStart(@javax.annotation.Nullable String firstStart) {
    this.firstStart = firstStart;
    return this;
  }

  /**
   * Get firstStart
   * @return firstStart
   */
  @javax.annotation.Nullable
  public String getFirstStart() {
    return firstStart;
  }

  public void setFirstStart(@javax.annotation.Nullable String firstStart) {
    this.firstStart = firstStart;
  }


  public ModelsAggregatedUsage lastEnd(@javax.annotation.Nullable String lastEnd) {
    this.lastEnd = lastEnd;
    return this;
  }

  /**
   * Get lastEnd
   * @return lastEnd
   */
  @javax.annotation.Nullable
  public String getLastEnd() {
    return lastEnd;
  }

  public void setLastEnd(@javax.annotation.Nullable String lastEnd) {
    this.lastEnd = lastEnd;
  }


  public ModelsAggregatedUsage sandboxCount(@javax.annotation.Nullable Integer sandboxCount) {
    this.sandboxCount = sandboxCount;
    return this;
  }

  /**
   * Get sandboxCount
   * @return sandboxCount
   */
  @javax.annotation.Nullable
  public Integer getSandboxCount() {
    return sandboxCount;
  }

  public void setSandboxCount(@javax.annotation.Nullable Integer sandboxCount) {
    this.sandboxCount = sandboxCount;
  }


  public ModelsAggregatedUsage totalCPUSeconds(@javax.annotation.Nullable Integer totalCPUSeconds) {
    this.totalCPUSeconds = totalCPUSeconds;
    return this;
  }

  /**
   * Get totalCPUSeconds
   * @return totalCPUSeconds
   */
  @javax.annotation.Nullable
  public Integer getTotalCPUSeconds() {
    return totalCPUSeconds;
  }

  public void setTotalCPUSeconds(@javax.annotation.Nullable Integer totalCPUSeconds) {
    this.totalCPUSeconds = totalCPUSeconds;
  }


  public ModelsAggregatedUsage totalDiskGBSeconds(@javax.annotation.Nullable Integer totalDiskGBSeconds) {
    this.totalDiskGBSeconds = totalDiskGBSeconds;
    return this;
  }

  /**
   * Get totalDiskGBSeconds
   * @return totalDiskGBSeconds
   */
  @javax.annotation.Nullable
  public Integer getTotalDiskGBSeconds() {
    return totalDiskGBSeconds;
  }

  public void setTotalDiskGBSeconds(@javax.annotation.Nullable Integer totalDiskGBSeconds) {
    this.totalDiskGBSeconds = totalDiskGBSeconds;
  }


  public ModelsAggregatedUsage totalGPUSeconds(@javax.annotation.Nullable Integer totalGPUSeconds) {
    this.totalGPUSeconds = totalGPUSeconds;
    return this;
  }

  /**
   * Get totalGPUSeconds
   * @return totalGPUSeconds
   */
  @javax.annotation.Nullable
  public Integer getTotalGPUSeconds() {
    return totalGPUSeconds;
  }

  public void setTotalGPUSeconds(@javax.annotation.Nullable Integer totalGPUSeconds) {
    this.totalGPUSeconds = totalGPUSeconds;
  }


  public ModelsAggregatedUsage totalPrice(@javax.annotation.Nullable BigDecimal totalPrice) {
    this.totalPrice = totalPrice;
    return this;
  }

  /**
   * Get totalPrice
   * @return totalPrice
   */
  @javax.annotation.Nullable
  public BigDecimal getTotalPrice() {
    return totalPrice;
  }

  public void setTotalPrice(@javax.annotation.Nullable BigDecimal totalPrice) {
    this.totalPrice = totalPrice;
  }


  public ModelsAggregatedUsage totalRAMGBSeconds(@javax.annotation.Nullable Integer totalRAMGBSeconds) {
    this.totalRAMGBSeconds = totalRAMGBSeconds;
    return this;
  }

  /**
   * Get totalRAMGBSeconds
   * @return totalRAMGBSeconds
   */
  @javax.annotation.Nullable
  public Integer getTotalRAMGBSeconds() {
    return totalRAMGBSeconds;
  }

  public void setTotalRAMGBSeconds(@javax.annotation.Nullable Integer totalRAMGBSeconds) {
    this.totalRAMGBSeconds = totalRAMGBSeconds;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ModelsAggregatedUsage instance itself
   */
  public ModelsAggregatedUsage putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsAggregatedUsage modelsAggregatedUsage = (ModelsAggregatedUsage) o;
    return Objects.equals(this.firstStart, modelsAggregatedUsage.firstStart) &&
        Objects.equals(this.lastEnd, modelsAggregatedUsage.lastEnd) &&
        Objects.equals(this.sandboxCount, modelsAggregatedUsage.sandboxCount) &&
        Objects.equals(this.totalCPUSeconds, modelsAggregatedUsage.totalCPUSeconds) &&
        Objects.equals(this.totalDiskGBSeconds, modelsAggregatedUsage.totalDiskGBSeconds) &&
        Objects.equals(this.totalGPUSeconds, modelsAggregatedUsage.totalGPUSeconds) &&
        Objects.equals(this.totalPrice, modelsAggregatedUsage.totalPrice) &&
        Objects.equals(this.totalRAMGBSeconds, modelsAggregatedUsage.totalRAMGBSeconds)&&
        Objects.equals(this.additionalProperties, modelsAggregatedUsage.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstStart, lastEnd, sandboxCount, totalCPUSeconds, totalDiskGBSeconds, totalGPUSeconds, totalPrice, totalRAMGBSeconds, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsAggregatedUsage {\n");
    sb.append("    firstStart: ").append(toIndentedString(firstStart)).append("\n");
    sb.append("    lastEnd: ").append(toIndentedString(lastEnd)).append("\n");
    sb.append("    sandboxCount: ").append(toIndentedString(sandboxCount)).append("\n");
    sb.append("    totalCPUSeconds: ").append(toIndentedString(totalCPUSeconds)).append("\n");
    sb.append("    totalDiskGBSeconds: ").append(toIndentedString(totalDiskGBSeconds)).append("\n");
    sb.append("    totalGPUSeconds: ").append(toIndentedString(totalGPUSeconds)).append("\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("    totalRAMGBSeconds: ").append(toIndentedString(totalRAMGBSeconds)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("firstStart", "lastEnd", "sandboxCount", "totalCPUSeconds", "totalDiskGBSeconds", "totalGPUSeconds", "totalPrice", "totalRAMGBSeconds"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ModelsAggregatedUsage
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ModelsAggregatedUsage.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ModelsAggregatedUsage is not found in the empty JSON string", ModelsAggregatedUsage.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("firstStart") != null && !jsonObj.get("firstStart").isJsonNull()) && !jsonObj.get("firstStart").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `firstStart` to be a primitive type in the JSON string but got `%s`", jsonObj.get("firstStart").toString()));
      }
      if ((jsonObj.get("lastEnd") != null && !jsonObj.get("lastEnd").isJsonNull()) && !jsonObj.get("lastEnd").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `lastEnd` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastEnd").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ModelsAggregatedUsage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ModelsAggregatedUsage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ModelsAggregatedUsage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ModelsAggregatedUsage.class));

       return (TypeAdapter<T>) new TypeAdapter<ModelsAggregatedUsage>() {
           @Override
           public void write(JsonWriter out, ModelsAggregatedUsage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ModelsAggregatedUsage read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             ModelsAggregatedUsage instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ModelsAggregatedUsage given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ModelsAggregatedUsage
   * @throws IOException if the JSON string is invalid with respect to ModelsAggregatedUsage
   */
  public static ModelsAggregatedUsage fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ModelsAggregatedUsage.class);
  }

  /**
   * Convert an instance of ModelsAggregatedUsage to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

