basePath: /
definitions:
  AgentServicePlugin:
    properties:
      name:
        type: string
      version:
        type: string
    type: object
  CreateWorkspace:
    properties:
      name:
        type: string
      provisioner:
        type: string
      repositories:
        items:
          type: string
        type: array
    type: object
  FRPSConfig:
    properties:
      domain:
        type: string
      port:
        type: integer
      protocol:
        type: string
    type: object
  GitProvider:
    properties:
      id:
        type: string
      token:
        type: string
      username:
        type: string
    type: object
  InstallPluginRequest:
    properties:
      downloadUrls:
        additionalProperties:
          type: string
        type: object
      name:
        type: string
    type: object
  NetworkKey:
    properties:
      key:
        type: string
    type: object
  Project:
    properties:
      authKey:
        type: string
      name:
        type: string
      repository:
        $ref: '#/definitions/Repository'
      workspaceId:
        type: string
    type: object
  ProjectInfo:
    properties:
      created:
        type: string
      finished:
        type: string
      isRunning:
        type: boolean
      name:
        type: string
      provisionerMetadata:
        type: string
      started:
        type: string
      workspaceId:
        type: string
    type: object
  ProvisionerPlugin:
    properties:
      name:
        type: string
      version:
        type: string
    type: object
  Repository:
    properties:
      branch:
        type: string
      owner:
        type: string
      path:
        type: string
      prNumber:
        type: integer
      sha:
        type: string
      source:
        type: string
      url:
        type: string
    type: object
  ServerConfig:
    properties:
      apiPort:
        type: integer
      frps:
        $ref: '#/definitions/FRPSConfig'
      gitProviders:
        items:
          $ref: '#/definitions/GitProvider'
        type: array
      headscalePort:
        type: integer
      id:
        type: string
      pluginRegistryUrl:
        type: string
      pluginsDir:
        type: string
      serverDownloadUrl:
        type: string
    type: object
  Workspace:
    properties:
      id:
        type: string
      name:
        type: string
      projects:
        items:
          $ref: '#/definitions/Project'
        type: array
      provisioner:
        $ref: '#/definitions/WorkspaceProvisioner'
    type: object
  WorkspaceInfo:
    properties:
      name:
        type: string
      projects:
        items:
          $ref: '#/definitions/ProjectInfo'
        type: array
      provisionerMetadata:
        type: string
    type: object
  WorkspaceProvisioner:
    properties:
      name:
        type: string
      profile:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Daytona Server API
  title: Daytona Server API
  version: 0.1.0
paths:
  /plugin/agent-service:
    get:
      consumes:
      - application/json
      description: List agent service plugins
      operationId: ListAgentServicePlugins
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/AgentServicePlugin'
            type: array
      summary: List agent service plugins
      tags:
      - plugin
  /plugin/agent-service/install:
    post:
      consumes:
      - application/json
      description: Install an agent service plugin
      operationId: InstallAgentServicePlugin
      parameters:
      - description: Plugin to install
        in: body
        name: plugin
        required: true
        schema:
          $ref: '#/definitions/InstallPluginRequest'
      responses:
        "200":
          description: OK
      summary: Install an agent service plugin
      tags:
      - plugin
  /plugin/agent-service/uninstall:
    post:
      consumes:
      - application/json
      description: Uninstall an agent service plugin
      operationId: UninstallAgentServicePlugin
      parameters:
      - description: Agent Service to uninstall
        in: path
        name: agent-service
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Uninstall an agent service plugin
      tags:
      - plugin
  /plugin/provisioner:
    get:
      consumes:
      - application/json
      description: List provisioner plugins
      operationId: ListProvisionerPlugins
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ProvisionerPlugin'
            type: array
      summary: List provisioner plugins
      tags:
      - plugin
  /plugin/provisioner/{provisioner}/uninstall:
    post:
      consumes:
      - application/json
      description: Uninstall a provisioner plugin
      operationId: UninstallProvisionerPlugin
      parameters:
      - description: Provisioner to uninstall
        in: path
        name: provisioner
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Uninstall a provisioner plugin
      tags:
      - plugin
  /plugin/provisioner/install:
    post:
      consumes:
      - application/json
      description: Install a provisioner plugin
      operationId: InstallProvisionerPlugin
      parameters:
      - description: Plugin to install
        in: body
        name: plugin
        required: true
        schema:
          $ref: '#/definitions/InstallPluginRequest'
      responses:
        "200":
          description: OK
      summary: Install a provisioner plugin
      tags:
      - plugin
  /server/config:
    get:
      description: Get the server configuration
      operationId: GetConfig
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ServerConfig'
      summary: Get the server configuration
      tags:
      - server
    post:
      consumes:
      - application/json
      description: Set the server configuration
      operationId: SetConfig
      parameters:
      - description: Server configuration
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/ServerConfig'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ServerConfig'
      summary: Set the server configuration
      tags:
      - server
  /server/network-key:
    post:
      description: Generate a new authentication key
      operationId: GenerateNetworkKey
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/NetworkKey'
      summary: Generate a new authentication key
      tags:
      - server
  /workspace:
    get:
      description: List workspaces info
      operationId: ListWorkspaces
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Workspace'
            type: array
      summary: List workspaces info
      tags:
      - workspace
    post:
      description: Create a workspace
      operationId: CreateWorkspace
      parameters:
      - description: Create workspace
        in: body
        name: workspace
        required: true
        schema:
          $ref: '#/definitions/CreateWorkspace'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Workspace'
      summary: Create a workspace
      tags:
      - workspace
  /workspace/{workspaceId}:
    delete:
      description: Remove workspace
      operationId: RemoveWorkspace
      parameters:
      - description: Workspace ID
        in: path
        name: workspaceId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Remove workspace
      tags:
      - workspace
    get:
      description: Get workspace info
      operationId: GetWorkspaceInfo
      parameters:
      - description: Workspace ID
        in: path
        name: workspaceId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/WorkspaceInfo'
      summary: Get workspace info
      tags:
      - workspace
  /workspace/{workspaceId}/{projectId}/start:
    post:
      description: Start project
      operationId: StartProject
      parameters:
      - description: Workspace ID
        in: path
        name: workspaceId
        required: true
        type: string
      - description: Project ID
        in: path
        name: projectId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Start project
      tags:
      - workspace
  /workspace/{workspaceId}/{projectId}/stop:
    post:
      description: Stop project
      operationId: StopProject
      parameters:
      - description: Workspace ID
        in: path
        name: workspaceId
        required: true
        type: string
      - description: Project ID
        in: path
        name: projectId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Stop project
      tags:
      - workspace
  /workspace/{workspaceId}/start:
    post:
      description: Start workspace
      operationId: StartWorkspace
      parameters:
      - description: Workspace ID
        in: path
        name: workspaceId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Start workspace
      tags:
      - workspace
  /workspace/{workspaceId}/stop:
    post:
      description: Stop workspace
      operationId: StopWorkspace
      parameters:
      - description: Workspace ID
        in: path
        name: workspaceId
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Stop workspace
      tags:
      - workspace
schemes:
- http
swagger: "2.0"
