/*
 * Copyright 2025 Daytona Platforms Inc.
 * SPDX-License-Identifier: AGPL-3.0
 */

import { Injectable, Logger, ServiceUnavailableException } from '@nestjs/common'
import { TypedConfigService } from '../../../config/typed-config.service'

// Default per-region control-plane URLs used by the layered volume backend.
//
// Each region has its own control-plane host; disks live in exactly one
// region and must be created against the matching host. The mapping below
// can be overridden per-region with `LAYERED_CONTROL_URL_<REGION>` env vars
// (with `-` replaced by `_`, e.g. `LAYERED_CONTROL_URL_AWS_US_EAST_1`) when a
// future region or staging endpoint becomes available.
const DEFAULT_CONTROL_URLS: Record<string, string> = {
  'aws-us-east-1': 'https://control.green.us-east-1.aws.prod.archil.com',
  'aws-eu-west-1': 'https://control.green.eu-west-1.aws.prod.archil.com',
  'aws-us-west-2': 'https://control.green.us-west-2.aws.prod.archil.com',
  'gcp-us-central1': 'https://control.blue.us-central1.gcp.prod.archil.com',
}

export interface LayeredDisk {
  diskId: string
  region: string
  // One-time mount token returned at disk creation time. This is the only
  // credential clients need to mount the disk; it grants read/write access
  // to the disk's bucket prefix. Cannot be retrieved again from the control
  // plane — store it (encrypted) on first receipt.
  mountToken: string
}

// External storage backing for a layered disk. Daytona always uses an
// S3 bucket as the backing store for layered volumes — vendor-managed
// storage is intentionally not exposed.
//
// Use the `s3` variant for AWS S3 buckets (the control plane resolves the
// endpoint from the bucket's region). Use `s3-compatible` for non-AWS S3
// endpoints such as MinIO or Cloudflare R2 — those require an explicit
// `bucketEndpoint` URL.
export type LayeredDiskMount =
  | {
      type: 's3'
      bucketName: string
      accessKeyId: string
      secretAccessKey: string
      sessionToken?: string
      bucketPrefix?: string
    }
  | {
      type: 's3-compatible'
      bucketName: string
      bucketEndpoint: string
      accessKeyId: string
      secretAccessKey: string
      bucketPrefix?: string
    }

export interface CreateLayeredDiskOptions {
  // Stable, idempotent name for the disk. Reusing the exact same name with
  // the same configuration is a no-op (200 OK); reusing it with different
  // configuration is a 409 conflict.
  name: string
  // Region the disk should live in. Defaults to `layered.defaultRegion`.
  region?: string
  // External storage backing for the disk. Required — Daytona never
  // provisions vendor-managed storage; every layered volume is backed by
  // a Daytona-owned S3 bucket.
  mount: LayeredDiskMount
}

interface ApiResponseEnvelope<T> {
  success: boolean
  error?: string
  data?: T
}

interface CreateDiskResponseData {
  diskId: string
  authorizedUsers?: Array<{
    type?: string
    token?: string
    identifier?: string
    nickname?: string
  }>
}

interface AddAuthorizedUserResponseData {
  // The new authorized user as returned by the control plane.
  type?: string
  token?: string
  identifier?: string
  nickname?: string
}

export interface MintMountKeyOptions {
  diskId: string
  region: string
  // Optional human-readable nickname forwarded to the control plane for
  // attribution (e.g. "sandbox-<id>"). Useful when debugging which sandbox
  // a given token belongs to.
  nickname?: string
}

@Injectable()
export class LayeredVolumeClient {
  private readonly logger = new Logger(LayeredVolumeClient.name)
  private readonly apiKey?: string
  private readonly defaultRegion: string

  constructor(private readonly configService: TypedConfigService) {
    this.apiKey = this.configService.get('layered.apiKey')
    this.defaultRegion = this.configService.get('layered.defaultRegion') || 'aws-us-east-1'
  }

  // Whether the layered control-plane integration is configured. The
  // layered volume backend requires this; volumes scheduled for that
  // backend will fail with a clear error when it isn't.
  isConfigured(): boolean {
    return Boolean(this.apiKey)
  }

  getDefaultRegion(): string {
    return this.defaultRegion
  }

  // Creates a layered disk and returns its ID, region, and the one-time
  // mount token generated by the control plane. Idempotent on `name`.
  //
  // Each Daytona volume maps 1:1 to its own layered disk so that the
  // returned mount token (which grants disk access) can serve as the
  // isolation boundary between organizations and users.
  async createDisk(opts: CreateLayeredDiskOptions): Promise<LayeredDisk> {
    this.assertConfigured()
    const region = opts.region || this.defaultRegion
    const baseUrl = this.resolveControlUrl(region)

    const res = await this.request<CreateDiskResponseData>(`${baseUrl}/api/disks`, {
      method: 'POST',
      body: JSON.stringify({
        name: opts.name,
        // The control plane takes a list of mounts; we always provision
        // exactly one S3 mount per disk so the disk is a 1:1 view of a
        // Daytona-owned bucket (optionally scoped to a prefix). No
        // vendor-managed storage path is supported.
        mounts: [opts.mount],
      }),
    })

    if (!res.diskId) {
      throw new Error('createDisk response missing diskId')
    }

    // Pull the auto-generated token user the API provisions on disk
    // creation. We only ever provision token-based users for Daytona
    // volumes; AWS STS users are out of scope here.
    const tokenUser = res.authorizedUsers?.find((u) => u.type === 'token' && u.token)
    if (!tokenUser?.token) {
      throw new Error(
        `createDisk response did not include a generated token (diskId=${res.diskId}). ` +
          `The disk exists but is not mountable; delete it manually or open a support ticket.`,
      )
    }

    return {
      diskId: res.diskId,
      region,
      mountToken: tokenUser.token,
    }
  }

  // Deletes a layered disk and all its associated resources. Treats 404 as
  // success so that retries after a partial delete are safe.
  async deleteDisk(diskId: string, region: string): Promise<void> {
    this.assertConfigured()
    const baseUrl = this.resolveControlUrl(region)

    await this.request<unknown>(`${baseUrl}/api/disks/${encodeURIComponent(diskId)}`, {
      method: 'DELETE',
      treat404AsOk: true,
    })
  }

  // Adds a new token-based authorized user to an existing disk and returns
  // its token. Used to mint per-(sandbox, volume) mount keys so a given
  // sandbox can be granted access independently from others and revoked
  // without invalidating the rest.
  async mintMountKey(opts: MintMountKeyOptions): Promise<string> {
    this.assertConfigured()
    const baseUrl = this.resolveControlUrl(opts.region)

    const res = await this.request<AddAuthorizedUserResponseData>(
      `${baseUrl}/api/disks/${encodeURIComponent(opts.diskId)}/authorized-users`,
      {
        method: 'POST',
        body: JSON.stringify({
          type: 'token',
          ...(opts.nickname ? { nickname: opts.nickname } : {}),
        }),
      },
    )

    if (!res?.token) {
      throw new Error(`mintMountKey response missing token for disk ${opts.diskId}`)
    }
    return res.token
  }

  // Revokes a previously minted token from a disk. Treats 404 as success so
  // double-revokes (e.g. after partial sandbox destroy) are safe.
  async revokeMountKey(diskId: string, region: string, token: string): Promise<void> {
    this.assertConfigured()
    const baseUrl = this.resolveControlUrl(region)

    await this.request<unknown>(
      `${baseUrl}/api/disks/${encodeURIComponent(diskId)}/authorized-users/${encodeURIComponent(token)}`,
      {
        method: 'DELETE',
        treat404AsOk: true,
      },
    )
  }

  private assertConfigured(): void {
    if (!this.apiKey) {
      throw new ServiceUnavailableException(
        'Layered volume control plane is not configured. Set LAYERED_API_KEY to enable the layered volume backend.',
      )
    }
  }

  private resolveControlUrl(region: string): string {
    const overrideKey = `LAYERED_CONTROL_URL_${region.toUpperCase().replace(/-/g, '_')}`
    const override = process.env[overrideKey]
    if (override) {
      return override.replace(/\/$/, '')
    }
    const fallback = DEFAULT_CONTROL_URLS[region]
    if (!fallback) {
      throw new Error(
        `Unknown layered region "${region}". Set ${overrideKey} to its control-plane URL or pick a documented region.`,
      )
    }
    return fallback
  }

  private async request<T>(
    url: string,
    init: { method: 'GET' | 'POST' | 'DELETE'; body?: string; treat404AsOk?: boolean },
  ): Promise<T> {
    const response = await fetch(url, {
      method: init.method,
      headers: {
        Authorization: `key-${this.apiKey}`,
        'Content-Type': 'application/json',
      },
      body: init.body,
    })

    if (init.treat404AsOk && response.status === 404) {
      return undefined as T
    }

    let envelope: ApiResponseEnvelope<T>
    const raw = await response.text()
    try {
      envelope = raw ? (JSON.parse(raw) as ApiResponseEnvelope<T>) : { success: response.ok }
    } catch {
      throw new Error(
        `Layered ${init.method} ${url} returned non-JSON response (status ${response.status}): ${raw.slice(0, 200)}`,
      )
    }

    if (!response.ok || envelope.success === false) {
      const message = envelope.error || `${init.method} ${url} failed with status ${response.status}`
      throw new Error(`Layered control plane error: ${message}`)
    }

    return envelope.data as T
  }
}
