/*
 * Daytona Toolbox API
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.toolbox.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BrowserStatusResponse
 */
public class BrowserStatusResponseTest {
    private final BrowserStatusResponse model = new BrowserStatusResponse();

    /**
     * Model tests for BrowserStatusResponse
     */
    @Test
    public void testBrowserStatusResponse() {
        // TODO: test BrowserStatusResponse
    }

    /**
     * Test the property 'localWebSocketDebuggerUrl'
     */
    @Test
    public void localWebSocketDebuggerUrlTest() {
        // TODO: test localWebSocketDebuggerUrl
    }

    /**
     * Test the property 'pid'
     */
    @Test
    public void pidTest() {
        // TODO: test pid
    }

    /**
     * Test the property 'port'
     */
    @Test
    public void portTest() {
        // TODO: test port
    }

    /**
     * Test the property 'proxyPath'
     */
    @Test
    public void proxyPathTest() {
        // TODO: test proxyPath
    }

    /**
     * Test the property 'running'
     */
    @Test
    public void runningTest() {
        // TODO: test running
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'webSocketDebuggerUrl'
     */
    @Test
    public void webSocketDebuggerUrlTest() {
        // TODO: test webSocketDebuggerUrl
    }

}
