/*
 * Daytona Toolbox API
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.toolbox.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MouseDragRequest
 */
public class MouseDragRequestTest {
    private final MouseDragRequest model = new MouseDragRequest();

    /**
     * Model tests for MouseDragRequest
     */
    @Test
    public void testMouseDragRequest() {
        // TODO: test MouseDragRequest
    }

    /**
     * Test the property 'button'
     */
    @Test
    public void buttonTest() {
        // TODO: test button
    }

    /**
     * Test the property 'endX'
     */
    @Test
    public void endXTest() {
        // TODO: test endX
    }

    /**
     * Test the property 'endY'
     */
    @Test
    public void endYTest() {
        // TODO: test endY
    }

    /**
     * Test the property 'startX'
     */
    @Test
    public void startXTest() {
        // TODO: test startX
    }

    /**
     * Test the property 'startY'
     */
    @Test
    public void startYTest() {
        // TODO: test startY
    }

}
