/*
 * Daytona Toolbox API
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.toolbox.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WorkDirResponse
 */
public class WorkDirResponseTest {
    private final WorkDirResponse model = new WorkDirResponse();

    /**
     * Model tests for WorkDirResponse
     */
    @Test
    public void testWorkDirResponse() {
        // TODO: test WorkDirResponse
    }

    /**
     * Test the property 'dir'
     */
    @Test
    public void dirTest() {
        // TODO: test dir
    }

}
