/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// SandboxListSortField the model 'SandboxListSortField'
type SandboxListSortField string

// List of SandboxListSortField
const (
	SANDBOXLISTSORTFIELD_NAME SandboxListSortField = "name"
	SANDBOXLISTSORTFIELD_CPU SandboxListSortField = "cpu"
	SANDBOXLISTSORTFIELD_MEMORY_GIB SandboxListSortField = "memoryGib"
	SANDBOXLISTSORTFIELD_DISK_GIB SandboxListSortField = "diskGib"
	SANDBOXLISTSORTFIELD_LAST_ACTIVITY_AT SandboxListSortField = "lastActivityAt"
	SANDBOXLISTSORTFIELD_CREATED_AT SandboxListSortField = "createdAt"
	SANDBOXLISTSORTFIELD_UNKNOWN_DEFAULT_OPEN_API SandboxListSortField = "11184809"
)

// All allowed values of SandboxListSortField enum
var AllowedSandboxListSortFieldEnumValues = []SandboxListSortField{
	"name",
	"cpu",
	"memoryGib",
	"diskGib",
	"lastActivityAt",
	"createdAt",
	"11184809",
}

func (v *SandboxListSortField) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SandboxListSortField(value)
	for _, existing := range AllowedSandboxListSortFieldEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = SANDBOXLISTSORTFIELD_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewSandboxListSortFieldFromValue returns a pointer to a valid SandboxListSortField
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSandboxListSortFieldFromValue(v string) (*SandboxListSortField, error) {
	ev := SandboxListSortField(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		enumValue := SANDBOXLISTSORTFIELD_UNKNOWN_DEFAULT_OPEN_API
		return &enumValue, nil
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SandboxListSortField) IsValid() bool {
	for _, existing := range AllowedSandboxListSortFieldEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SandboxListSortField value
func (v SandboxListSortField) Ptr() *SandboxListSortField {
	return &v
}

type NullableSandboxListSortField struct {
	value *SandboxListSortField
	isSet bool
}

func (v NullableSandboxListSortField) Get() *SandboxListSortField {
	return v.value
}

func (v *NullableSandboxListSortField) Set(val *SandboxListSortField) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxListSortField) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxListSortField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxListSortField(val *SandboxListSortField) *NullableSandboxListSortField {
	return &NullableSandboxListSortField{value: val, isSet: true}
}

func (v NullableSandboxListSortField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxListSortField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

