/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the EmptyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmptyResponse{}

// EmptyResponse struct for EmptyResponse
type EmptyResponse struct {
	// Whether the operation was successful
	Success bool `json:"success"`
}

type _EmptyResponse EmptyResponse

// NewEmptyResponse instantiates a new EmptyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmptyResponse(success bool) *EmptyResponse {
	this := EmptyResponse{}
	this.Success = success
	return &this
}

// NewEmptyResponseWithDefaults instantiates a new EmptyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmptyResponseWithDefaults() *EmptyResponse {
	this := EmptyResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *EmptyResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *EmptyResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *EmptyResponse) SetSuccess(v bool) {
	o.Success = v
}

func (o EmptyResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmptyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	return toSerialize, nil
}

func (o *EmptyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmptyResponse := _EmptyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmptyResponse)

	if err != nil {
		return err
	}

	*o = EmptyResponse(varEmptyResponse)

	return err
}

type NullableEmptyResponse struct {
	value *EmptyResponse
	isSet bool
}

func (v NullableEmptyResponse) Get() *EmptyResponse {
	return v.value
}

func (v *NullableEmptyResponse) Set(val *EmptyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmptyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmptyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmptyResponse(val *EmptyResponse) *NullableEmptyResponse {
	return &NullableEmptyResponse{value: val, isSet: true}
}

func (v NullableEmptyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmptyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
