/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the ToolboxProxyUrl type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ToolboxProxyUrl{}

// ToolboxProxyUrl struct for ToolboxProxyUrl
type ToolboxProxyUrl struct {
	// The toolbox proxy URL for the sandbox
	Url string `json:"url"`
	AdditionalProperties map[string]interface{}
}

type _ToolboxProxyUrl ToolboxProxyUrl

// NewToolboxProxyUrl instantiates a new ToolboxProxyUrl object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToolboxProxyUrl(url string) *ToolboxProxyUrl {
	this := ToolboxProxyUrl{}
	this.Url = url
	return &this
}

// NewToolboxProxyUrlWithDefaults instantiates a new ToolboxProxyUrl object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewToolboxProxyUrlWithDefaults() *ToolboxProxyUrl {
	this := ToolboxProxyUrl{}
	return &this
}

// GetUrl returns the Url field value
func (o *ToolboxProxyUrl) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ToolboxProxyUrl) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ToolboxProxyUrl) SetUrl(v string) {
	o.Url = v
}

func (o ToolboxProxyUrl) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ToolboxProxyUrl) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ToolboxProxyUrl) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varToolboxProxyUrl := _ToolboxProxyUrl{}

	err = json.Unmarshal(data, &varToolboxProxyUrl)

	if err != nil {
		return err
	}

	*o = ToolboxProxyUrl(varToolboxProxyUrl)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableToolboxProxyUrl struct {
	value *ToolboxProxyUrl
	isSet bool
}

func (v NullableToolboxProxyUrl) Get() *ToolboxProxyUrl {
	return v.value
}

func (v *NullableToolboxProxyUrl) Set(val *ToolboxProxyUrl) {
	v.value = val
	v.isSet = true
}

func (v NullableToolboxProxyUrl) IsSet() bool {
	return v.isSet
}

func (v *NullableToolboxProxyUrl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToolboxProxyUrl(val *ToolboxProxyUrl) *NullableToolboxProxyUrl {
	return &NullableToolboxProxyUrl{value: val, isSet: true}
}

func (v NullableToolboxProxyUrl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToolboxProxyUrl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


