/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the DisplayDataDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DisplayDataDto{}

// DisplayDataDto struct for DisplayDataDto
type DisplayDataDto struct {
	Formats []string `json:"formats"`
	// Mime → payload (base64 for binary).
	Data map[string]string `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _DisplayDataDto DisplayDataDto

// NewDisplayDataDto instantiates a new DisplayDataDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisplayDataDto(formats []string, data map[string]string) *DisplayDataDto {
	this := DisplayDataDto{}
	this.Formats = formats
	this.Data = data
	return &this
}

// NewDisplayDataDtoWithDefaults instantiates a new DisplayDataDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisplayDataDtoWithDefaults() *DisplayDataDto {
	this := DisplayDataDto{}
	return &this
}

// GetFormats returns the Formats field value
func (o *DisplayDataDto) GetFormats() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Formats
}

// GetFormatsOk returns a tuple with the Formats field value
// and a boolean to check if the value has been set.
func (o *DisplayDataDto) GetFormatsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Formats, true
}

// SetFormats sets field value
func (o *DisplayDataDto) SetFormats(v []string) {
	o.Formats = v
}

// GetData returns the Data field value
func (o *DisplayDataDto) GetData() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DisplayDataDto) GetDataOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DisplayDataDto) SetData(v map[string]string) {
	o.Data = v
}

func (o DisplayDataDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DisplayDataDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["formats"] = o.Formats
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DisplayDataDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"formats",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDisplayDataDto := _DisplayDataDto{}

	err = json.Unmarshal(data, &varDisplayDataDto)

	if err != nil {
		return err
	}

	*o = DisplayDataDto(varDisplayDataDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "formats")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDisplayDataDto struct {
	value *DisplayDataDto
	isSet bool
}

func (v NullableDisplayDataDto) Get() *DisplayDataDto {
	return v.value
}

func (v *NullableDisplayDataDto) Set(val *DisplayDataDto) {
	v.value = val
	v.isSet = true
}

func (v NullableDisplayDataDto) IsSet() bool {
	return v.isSet
}

func (v *NullableDisplayDataDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisplayDataDto(val *DisplayDataDto) *NullableDisplayDataDto {
	return &NullableDisplayDataDto{value: val, isSet: true}
}

func (v NullableDisplayDataDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisplayDataDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


