/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the SessionDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionDto{}

// SessionDto struct for SessionDto
type SessionDto struct {
	Id string `json:"id"`
	Language string `json:"language"`
	Cwd *string `json:"cwd,omitempty"`
	CreatedAt string `json:"createdAt"`
	LastUsedAt *string `json:"lastUsedAt,omitempty"`
	// Computed expiry: min(lastUsedAt + idleTtl, createdAt + absoluteTtl). After this point the context will surface as SessionExpiredError.
	ExpiresAt string `json:"expiresAt"`
	// Direct-to-sandbox access bundle. Present on createSession / POST /sessions/transients responses and refreshable via GET /sessions/:id/access. Omitted on listSessions to keep payloads small.
	Access *SessionAccessDto `json:"access,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SessionDto SessionDto

// NewSessionDto instantiates a new SessionDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionDto(id string, language string, createdAt string, expiresAt string) *SessionDto {
	this := SessionDto{}
	this.Id = id
	this.Language = language
	this.CreatedAt = createdAt
	this.ExpiresAt = expiresAt
	return &this
}

// NewSessionDtoWithDefaults instantiates a new SessionDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionDtoWithDefaults() *SessionDto {
	this := SessionDto{}
	return &this
}

// GetId returns the Id field value
func (o *SessionDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SessionDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SessionDto) SetId(v string) {
	o.Id = v
}

// GetLanguage returns the Language field value
func (o *SessionDto) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *SessionDto) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *SessionDto) SetLanguage(v string) {
	o.Language = v
}

// GetCwd returns the Cwd field value if set, zero value otherwise.
func (o *SessionDto) GetCwd() string {
	if o == nil || IsNil(o.Cwd) {
		var ret string
		return ret
	}
	return *o.Cwd
}

// GetCwdOk returns a tuple with the Cwd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionDto) GetCwdOk() (*string, bool) {
	if o == nil || IsNil(o.Cwd) {
		return nil, false
	}
	return o.Cwd, true
}

// HasCwd returns a boolean if a field has been set.
func (o *SessionDto) HasCwd() bool {
	if o != nil && !IsNil(o.Cwd) {
		return true
	}

	return false
}

// SetCwd gets a reference to the given string and assigns it to the Cwd field.
func (o *SessionDto) SetCwd(v string) {
	o.Cwd = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *SessionDto) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SessionDto) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SessionDto) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetLastUsedAt returns the LastUsedAt field value if set, zero value otherwise.
func (o *SessionDto) GetLastUsedAt() string {
	if o == nil || IsNil(o.LastUsedAt) {
		var ret string
		return ret
	}
	return *o.LastUsedAt
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionDto) GetLastUsedAtOk() (*string, bool) {
	if o == nil || IsNil(o.LastUsedAt) {
		return nil, false
	}
	return o.LastUsedAt, true
}

// HasLastUsedAt returns a boolean if a field has been set.
func (o *SessionDto) HasLastUsedAt() bool {
	if o != nil && !IsNil(o.LastUsedAt) {
		return true
	}

	return false
}

// SetLastUsedAt gets a reference to the given string and assigns it to the LastUsedAt field.
func (o *SessionDto) SetLastUsedAt(v string) {
	o.LastUsedAt = &v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *SessionDto) GetExpiresAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *SessionDto) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *SessionDto) SetExpiresAt(v string) {
	o.ExpiresAt = v
}

// GetAccess returns the Access field value if set, zero value otherwise.
func (o *SessionDto) GetAccess() SessionAccessDto {
	if o == nil || IsNil(o.Access) {
		var ret SessionAccessDto
		return ret
	}
	return *o.Access
}

// GetAccessOk returns a tuple with the Access field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionDto) GetAccessOk() (*SessionAccessDto, bool) {
	if o == nil || IsNil(o.Access) {
		return nil, false
	}
	return o.Access, true
}

// HasAccess returns a boolean if a field has been set.
func (o *SessionDto) HasAccess() bool {
	if o != nil && !IsNil(o.Access) {
		return true
	}

	return false
}

// SetAccess gets a reference to the given SessionAccessDto and assigns it to the Access field.
func (o *SessionDto) SetAccess(v SessionAccessDto) {
	o.Access = &v
}

func (o SessionDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["language"] = o.Language
	if !IsNil(o.Cwd) {
		toSerialize["cwd"] = o.Cwd
	}
	toSerialize["createdAt"] = o.CreatedAt
	if !IsNil(o.LastUsedAt) {
		toSerialize["lastUsedAt"] = o.LastUsedAt
	}
	toSerialize["expiresAt"] = o.ExpiresAt
	if !IsNil(o.Access) {
		toSerialize["access"] = o.Access
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SessionDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"language",
		"createdAt",
		"expiresAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionDto := _SessionDto{}

	err = json.Unmarshal(data, &varSessionDto)

	if err != nil {
		return err
	}

	*o = SessionDto(varSessionDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "language")
		delete(additionalProperties, "cwd")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "lastUsedAt")
		delete(additionalProperties, "expiresAt")
		delete(additionalProperties, "access")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSessionDto struct {
	value *SessionDto
	isSet bool
}

func (v NullableSessionDto) Get() *SessionDto {
	return v.value
}

func (v *NullableSessionDto) Set(val *SessionDto) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionDto) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionDto(val *SessionDto) *NullableSessionDto {
	return &NullableSessionDto{value: val, isSet: true}
}

func (v NullableSessionDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


