/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UserPublicKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserPublicKey{}

// UserPublicKey struct for UserPublicKey
type UserPublicKey struct {
	// Public key
	Key string `json:"key"`
	// Key name
	Name string `json:"name"`
}

type _UserPublicKey UserPublicKey

// NewUserPublicKey instantiates a new UserPublicKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserPublicKey(key string, name string) *UserPublicKey {
	this := UserPublicKey{}
	this.Key = key
	this.Name = name
	return &this
}

// NewUserPublicKeyWithDefaults instantiates a new UserPublicKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserPublicKeyWithDefaults() *UserPublicKey {
	this := UserPublicKey{}
	return &this
}

// GetKey returns the Key field value
func (o *UserPublicKey) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *UserPublicKey) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *UserPublicKey) SetKey(v string) {
	o.Key = v
}

// GetName returns the Name field value
func (o *UserPublicKey) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UserPublicKey) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UserPublicKey) SetName(v string) {
	o.Name = v
}

func (o UserPublicKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserPublicKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *UserPublicKey) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserPublicKey := _UserPublicKey{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserPublicKey)

	if err != nil {
		return err
	}

	*o = UserPublicKey(varUserPublicKey)

	return err
}

type NullableUserPublicKey struct {
	value *UserPublicKey
	isSet bool
}

func (v NullableUserPublicKey) Get() *UserPublicKey {
	return v.value
}

func (v *NullableUserPublicKey) Set(val *UserPublicKey) {
	v.value = val
	v.isSet = true
}

func (v NullableUserPublicKey) IsSet() bool {
	return v.isSet
}

func (v *NullableUserPublicKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserPublicKey(val *UserPublicKey) *NullableUserPublicKey {
	return &NullableUserPublicKey{value: val, isSet: true}
}

func (v NullableUserPublicKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserPublicKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
