/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RegionDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegionDto{}

// RegionDto struct for RegionDto
type RegionDto struct {
	// Region code
	Code string `json:"code"`
	// Region name
	Name string `json:"name"`
	// Organization ID
	OrganizationId string `json:"organizationId"`
	// Docker registry ID (optional)
	DockerRegistryId NullableString `json:"dockerRegistryId"`
	// Creation timestamp
	CreatedAt string `json:"createdAt"`
	// Last update timestamp
	UpdatedAt string `json:"updatedAt"`
}

type _RegionDto RegionDto

// NewRegionDto instantiates a new RegionDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegionDto(code string, name string, organizationId string, dockerRegistryId NullableString, createdAt string, updatedAt string) *RegionDto {
	this := RegionDto{}
	this.Code = code
	this.Name = name
	this.OrganizationId = organizationId
	this.DockerRegistryId = dockerRegistryId
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewRegionDtoWithDefaults instantiates a new RegionDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegionDtoWithDefaults() *RegionDto {
	this := RegionDto{}
	return &this
}

// GetCode returns the Code field value
func (o *RegionDto) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *RegionDto) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *RegionDto) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *RegionDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RegionDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RegionDto) SetName(v string) {
	o.Name = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *RegionDto) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *RegionDto) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *RegionDto) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetDockerRegistryId returns the DockerRegistryId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *RegionDto) GetDockerRegistryId() string {
	if o == nil || o.DockerRegistryId.Get() == nil {
		var ret string
		return ret
	}

	return *o.DockerRegistryId.Get()
}

// GetDockerRegistryIdOk returns a tuple with the DockerRegistryId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RegionDto) GetDockerRegistryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DockerRegistryId.Get(), o.DockerRegistryId.IsSet()
}

// SetDockerRegistryId sets field value
func (o *RegionDto) SetDockerRegistryId(v string) {
	o.DockerRegistryId.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *RegionDto) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *RegionDto) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *RegionDto) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *RegionDto) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *RegionDto) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *RegionDto) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o RegionDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegionDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	toSerialize["organizationId"] = o.OrganizationId
	toSerialize["dockerRegistryId"] = o.DockerRegistryId.Get()
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *RegionDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"name",
		"organizationId",
		"dockerRegistryId",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegionDto := _RegionDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegionDto)

	if err != nil {
		return err
	}

	*o = RegionDto(varRegionDto)

	return err
}

type NullableRegionDto struct {
	value *RegionDto
	isSet bool
}

func (v NullableRegionDto) Get() *RegionDto {
	return v.value
}

func (v *NullableRegionDto) Set(val *RegionDto) {
	v.value = val
	v.isSet = true
}

func (v NullableRegionDto) IsSet() bool {
	return v.isSet
}

func (v *NullableRegionDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegionDto(val *RegionDto) *NullableRegionDto {
	return &NullableRegionDto{value: val, isSet: true}
}

func (v NullableRegionDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegionDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
