/*
 * Copyright Daytona Platforms Inc.
 * SPDX-License-Identifier: AGPL-3.0
 */

export enum ApiErrorCode {
  SANDBOX_STATE_CHANGE_IN_PROGRESS = 'SANDBOX_STATE_CHANGE_IN_PROGRESS',
  SANDBOX_STATE_ERROR = 'SANDBOX_STATE_ERROR',
  SANDBOX_BACKUP_STATE_ERROR = 'SANDBOX_BACKUP_STATE_ERROR',
  SANDBOX_OPERATION_NOT_SUPPORTED = 'SANDBOX_OPERATION_NOT_SUPPORTED',
  SANDBOX_DISK_EXPANSION_LIMIT = 'SANDBOX_DISK_EXPANSION_LIMIT',
  SNAPSHOT_STATE_CHANGE_IN_PROGRESS = 'SNAPSHOT_STATE_CHANGE_IN_PROGRESS',
  ORGANIZATION_QUOTA_EXCEEDED = 'ORGANIZATION_QUOTA_EXCEEDED',
  ORGANIZATION_SUSPENDED = 'ORGANIZATION_SUSPENDED',
  DEFAULT_REGION_REQUIRED = 'DEFAULT_REGION_REQUIRED',
  API_KEY_EXPIRED = 'API_KEY_EXPIRED',
  VOLUME_IN_USE = 'VOLUME_IN_USE',
  NO_AVAILABLE_RUNNERS = 'NO_AVAILABLE_RUNNERS',
  SANDBOX_RUNNER_NOT_FOUND = 'SANDBOX_RUNNER_NOT_FOUND',
}
