/*
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.api.client.api;

import io.daytona.api.client.ApiException;
import io.daytona.api.client.model.ChangeVolumeBackend;
import io.daytona.api.client.model.CreateVolume;
import io.daytona.api.client.model.VolumeDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VolumesApi
 */
@Disabled
public class VolumesApiTest {

    private final VolumesApi api = new VolumesApi();

    /**
     * Change a volume&#39;s backend
     *
     * Switches an existing volume between the s3fuse and experimental backends in place. The volume&#39;s S3 bucket and data are preserved; only the mount strategy changes. Refuses to switch while any sandbox referencing the volume is running.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void changeVolumeBackendTest() throws ApiException {
        String volumeId = null;
        ChangeVolumeBackend changeVolumeBackend = null;
        String xDaytonaOrganizationID = null;
        VolumeDto response = api.changeVolumeBackend(volumeId, changeVolumeBackend, xDaytonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Create a new volume
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createVolumeTest() throws ApiException {
        CreateVolume createVolume = null;
        String xDaytonaOrganizationID = null;
        VolumeDto response = api.createVolume(createVolume, xDaytonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Delete volume
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteVolumeTest() throws ApiException {
        String volumeId = null;
        String xDaytonaOrganizationID = null;
        api.deleteVolume(volumeId, xDaytonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Get volume details
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVolumeTest() throws ApiException {
        String volumeId = null;
        String xDaytonaOrganizationID = null;
        VolumeDto response = api.getVolume(volumeId, xDaytonaOrganizationID);
        // TODO: test validations
    }

    /**
     * Get volume details by name
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVolumeByNameTest() throws ApiException {
        String name = null;
        String xDaytonaOrganizationID = null;
        VolumeDto response = api.getVolumeByName(name, xDaytonaOrganizationID);
        // TODO: test validations
    }

    /**
     * List all volumes
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listVolumesTest() throws ApiException {
        String xDaytonaOrganizationID = null;
        Boolean includeDeleted = null;
        List<VolumeDto> response = api.listVolumes(xDaytonaOrganizationID, includeDeleted);
        // TODO: test validations
    }

}
