/*
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.api.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AdminCreateRunner
 */
public class AdminCreateRunnerTest {
    private final AdminCreateRunner model = new AdminCreateRunner();

    /**
     * Model tests for AdminCreateRunner
     */
    @Test
    public void testAdminCreateRunner() {
        // TODO: test AdminCreateRunner
    }

    /**
     * Test the property 'regionId'
     */
    @Test
    public void regionIdTest() {
        // TODO: test regionId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'apiKey'
     */
    @Test
    public void apiKeyTest() {
        // TODO: test apiKey
    }

    /**
     * Test the property 'apiVersion'
     */
    @Test
    public void apiVersionTest() {
        // TODO: test apiVersion
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'apiUrl'
     */
    @Test
    public void apiUrlTest() {
        // TODO: test apiUrl
    }

    /**
     * Test the property 'proxyUrl'
     */
    @Test
    public void proxyUrlTest() {
        // TODO: test proxyUrl
    }

    /**
     * Test the property 'cpu'
     */
    @Test
    public void cpuTest() {
        // TODO: test cpu
    }

    /**
     * Test the property 'memoryGiB'
     */
    @Test
    public void memoryGiBTest() {
        // TODO: test memoryGiB
    }

    /**
     * Test the property 'diskGiB'
     */
    @Test
    public void diskGiBTest() {
        // TODO: test diskGiB
    }

}
