/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Daytona.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Daytona.ApiClient.Client.OpenAPIDateConverter;

namespace Daytona.ApiClient.Model
{
    /// <summary>
    /// CompletionContext
    /// </summary>
    [DataContract(Name = "CompletionContext")]
    public partial class CompletionContext : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompletionContext" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CompletionContext() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CompletionContext" /> class.
        /// </summary>
        /// <param name="triggerKind">triggerKind (required).</param>
        /// <param name="triggerCharacter">triggerCharacter.</param>
        public CompletionContext(decimal triggerKind = default(decimal), string triggerCharacter = default(string))
        {
            this.TriggerKind = triggerKind;
            this.TriggerCharacter = triggerCharacter;
        }

        /// <summary>
        /// Gets or Sets TriggerKind
        /// </summary>
        [DataMember(Name = "triggerKind", IsRequired = true, EmitDefaultValue = true)]
        public decimal TriggerKind { get; set; }

        /// <summary>
        /// Gets or Sets TriggerCharacter
        /// </summary>
        [DataMember(Name = "triggerCharacter", EmitDefaultValue = false)]
        public string TriggerCharacter { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CompletionContext {\n");
            sb.Append("  TriggerKind: ").Append(TriggerKind).Append("\n");
            sb.Append("  TriggerCharacter: ").Append(TriggerCharacter).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
