=begin
#Daytona Daemon API

#Daytona Daemon API

The version of the OpenAPI document: v0.0.0-dev

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

module DaytonaToolboxApiClient
  VERSION = '1.0.0'
end
