// AUTO-GENERATED by hack/error-codes/main.go — do not edit.
// Run `go run hack/error-codes/main.go` to regenerate.
//
// Mirrors apps/proxy/pkg/proxy/errors.go::ProxyErrorCode.

package io.daytona.sdk.codes;

public enum ProxyErrorCode {
    SANDBOX_NOT_STARTED("SANDBOX_NOT_STARTED"),
    SANDBOX_NOT_FOUND("SANDBOX_NOT_FOUND"),
    RUNNER_UNREACHABLE("RUNNER_UNREACHABLE");

    private final String value;

    ProxyErrorCode(String value) { this.value = value; }

    public String getValue() { return value; }

    public static ProxyErrorCode fromValue(String value) {
        for (ProxyErrorCode code : values()) {
            if (code.value.equals(value)) return code;
        }
        return null;
    }
}
