# coding: utf-8

"""
    Daytona

    Daytona AI platform API Docs

    The version of the OpenAPI document: 1.0
    Contact: support@daytona.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from daytona_api_client_async.models.job_status import JobStatus
from daytona_api_client_async.models.job_type import JobType
from typing import Optional, Set
from typing_extensions import Self

class Job(BaseModel):
    """
    Job
    """ # noqa: E501
    id: StrictStr = Field(description="The ID of the job")
    type: JobType = Field(description="The type of the job")
    status: JobStatus = Field(description="The status of the job")
    resource_type: StrictStr = Field(description="The type of resource this job operates on", alias="resourceType")
    resource_id: StrictStr = Field(description="The ID of the resource this job operates on (sandboxId, snapshotRef, etc.)", alias="resourceId")
    payload: Optional[StrictStr] = Field(default=None, description="Job-specific JSON-encoded payload data (operational metadata)")
    trace_context: Optional[Dict[str, Any]] = Field(default=None, description="OpenTelemetry trace context for distributed tracing (W3C Trace Context format)", alias="traceContext")
    error_message: Optional[StrictStr] = Field(default=None, description="Error message if the job failed", alias="errorMessage")
    created_at: StrictStr = Field(description="The creation timestamp of the job", alias="createdAt")
    updated_at: Optional[StrictStr] = Field(default=None, description="The last update timestamp of the job", alias="updatedAt")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "type", "status", "resourceType", "resourceId", "payload", "traceContext", "errorMessage", "createdAt", "updatedAt"]

    @field_validator('resource_type')
    def resource_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['SANDBOX', 'SNAPSHOT', 'BACKUP']):
            raise ValueError("must be one of enum values ('SANDBOX', 'SNAPSHOT', 'BACKUP')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Job from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Job from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "status": obj.get("status"),
            "resourceType": obj.get("resourceType"),
            "resourceId": obj.get("resourceId"),
            "payload": obj.get("payload"),
            "traceContext": obj.get("traceContext"),
            "errorMessage": obj.get("errorMessage"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


