/*
Daytona Analytics API

Daytona Analytics API - Read-only telemetry and usage data. Authenticated via Daytona API keys or JWT tokens.

API version: v0.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analyticsapiclient

import (
	"encoding/json"
)

// checks if the ModelsUsageChartPoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsUsageChartPoint{}

// ModelsUsageChartPoint struct for ModelsUsageChartPoint
type ModelsUsageChartPoint struct {
	Cpu *int32 `json:"cpu,omitempty"`
	CpuPrice *float32 `json:"cpuPrice,omitempty"`
	DiskGB *int32 `json:"diskGB,omitempty"`
	DiskPrice *float32 `json:"diskPrice,omitempty"`
	RamGB *int32 `json:"ramGB,omitempty"`
	RamPrice *float32 `json:"ramPrice,omitempty"`
	Time *string `json:"time,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ModelsUsageChartPoint ModelsUsageChartPoint

// NewModelsUsageChartPoint instantiates a new ModelsUsageChartPoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsUsageChartPoint() *ModelsUsageChartPoint {
	this := ModelsUsageChartPoint{}
	return &this
}

// NewModelsUsageChartPointWithDefaults instantiates a new ModelsUsageChartPoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsUsageChartPointWithDefaults() *ModelsUsageChartPoint {
	this := ModelsUsageChartPoint{}
	return &this
}

// GetCpu returns the Cpu field value if set, zero value otherwise.
func (o *ModelsUsageChartPoint) GetCpu() int32 {
	if o == nil || IsNil(o.Cpu) {
		var ret int32
		return ret
	}
	return *o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUsageChartPoint) GetCpuOk() (*int32, bool) {
	if o == nil || IsNil(o.Cpu) {
		return nil, false
	}
	return o.Cpu, true
}

// HasCpu returns a boolean if a field has been set.
func (o *ModelsUsageChartPoint) HasCpu() bool {
	if o != nil && !IsNil(o.Cpu) {
		return true
	}

	return false
}

// SetCpu gets a reference to the given int32 and assigns it to the Cpu field.
func (o *ModelsUsageChartPoint) SetCpu(v int32) {
	o.Cpu = &v
}

// GetCpuPrice returns the CpuPrice field value if set, zero value otherwise.
func (o *ModelsUsageChartPoint) GetCpuPrice() float32 {
	if o == nil || IsNil(o.CpuPrice) {
		var ret float32
		return ret
	}
	return *o.CpuPrice
}

// GetCpuPriceOk returns a tuple with the CpuPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUsageChartPoint) GetCpuPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.CpuPrice) {
		return nil, false
	}
	return o.CpuPrice, true
}

// HasCpuPrice returns a boolean if a field has been set.
func (o *ModelsUsageChartPoint) HasCpuPrice() bool {
	if o != nil && !IsNil(o.CpuPrice) {
		return true
	}

	return false
}

// SetCpuPrice gets a reference to the given float32 and assigns it to the CpuPrice field.
func (o *ModelsUsageChartPoint) SetCpuPrice(v float32) {
	o.CpuPrice = &v
}

// GetDiskGB returns the DiskGB field value if set, zero value otherwise.
func (o *ModelsUsageChartPoint) GetDiskGB() int32 {
	if o == nil || IsNil(o.DiskGB) {
		var ret int32
		return ret
	}
	return *o.DiskGB
}

// GetDiskGBOk returns a tuple with the DiskGB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUsageChartPoint) GetDiskGBOk() (*int32, bool) {
	if o == nil || IsNil(o.DiskGB) {
		return nil, false
	}
	return o.DiskGB, true
}

// HasDiskGB returns a boolean if a field has been set.
func (o *ModelsUsageChartPoint) HasDiskGB() bool {
	if o != nil && !IsNil(o.DiskGB) {
		return true
	}

	return false
}

// SetDiskGB gets a reference to the given int32 and assigns it to the DiskGB field.
func (o *ModelsUsageChartPoint) SetDiskGB(v int32) {
	o.DiskGB = &v
}

// GetDiskPrice returns the DiskPrice field value if set, zero value otherwise.
func (o *ModelsUsageChartPoint) GetDiskPrice() float32 {
	if o == nil || IsNil(o.DiskPrice) {
		var ret float32
		return ret
	}
	return *o.DiskPrice
}

// GetDiskPriceOk returns a tuple with the DiskPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUsageChartPoint) GetDiskPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.DiskPrice) {
		return nil, false
	}
	return o.DiskPrice, true
}

// HasDiskPrice returns a boolean if a field has been set.
func (o *ModelsUsageChartPoint) HasDiskPrice() bool {
	if o != nil && !IsNil(o.DiskPrice) {
		return true
	}

	return false
}

// SetDiskPrice gets a reference to the given float32 and assigns it to the DiskPrice field.
func (o *ModelsUsageChartPoint) SetDiskPrice(v float32) {
	o.DiskPrice = &v
}

// GetRamGB returns the RamGB field value if set, zero value otherwise.
func (o *ModelsUsageChartPoint) GetRamGB() int32 {
	if o == nil || IsNil(o.RamGB) {
		var ret int32
		return ret
	}
	return *o.RamGB
}

// GetRamGBOk returns a tuple with the RamGB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUsageChartPoint) GetRamGBOk() (*int32, bool) {
	if o == nil || IsNil(o.RamGB) {
		return nil, false
	}
	return o.RamGB, true
}

// HasRamGB returns a boolean if a field has been set.
func (o *ModelsUsageChartPoint) HasRamGB() bool {
	if o != nil && !IsNil(o.RamGB) {
		return true
	}

	return false
}

// SetRamGB gets a reference to the given int32 and assigns it to the RamGB field.
func (o *ModelsUsageChartPoint) SetRamGB(v int32) {
	o.RamGB = &v
}

// GetRamPrice returns the RamPrice field value if set, zero value otherwise.
func (o *ModelsUsageChartPoint) GetRamPrice() float32 {
	if o == nil || IsNil(o.RamPrice) {
		var ret float32
		return ret
	}
	return *o.RamPrice
}

// GetRamPriceOk returns a tuple with the RamPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUsageChartPoint) GetRamPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.RamPrice) {
		return nil, false
	}
	return o.RamPrice, true
}

// HasRamPrice returns a boolean if a field has been set.
func (o *ModelsUsageChartPoint) HasRamPrice() bool {
	if o != nil && !IsNil(o.RamPrice) {
		return true
	}

	return false
}

// SetRamPrice gets a reference to the given float32 and assigns it to the RamPrice field.
func (o *ModelsUsageChartPoint) SetRamPrice(v float32) {
	o.RamPrice = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *ModelsUsageChartPoint) GetTime() string {
	if o == nil || IsNil(o.Time) {
		var ret string
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsUsageChartPoint) GetTimeOk() (*string, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *ModelsUsageChartPoint) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given string and assigns it to the Time field.
func (o *ModelsUsageChartPoint) SetTime(v string) {
	o.Time = &v
}

func (o ModelsUsageChartPoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsUsageChartPoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cpu) {
		toSerialize["cpu"] = o.Cpu
	}
	if !IsNil(o.CpuPrice) {
		toSerialize["cpuPrice"] = o.CpuPrice
	}
	if !IsNil(o.DiskGB) {
		toSerialize["diskGB"] = o.DiskGB
	}
	if !IsNil(o.DiskPrice) {
		toSerialize["diskPrice"] = o.DiskPrice
	}
	if !IsNil(o.RamGB) {
		toSerialize["ramGB"] = o.RamGB
	}
	if !IsNil(o.RamPrice) {
		toSerialize["ramPrice"] = o.RamPrice
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ModelsUsageChartPoint) UnmarshalJSON(data []byte) (err error) {
	varModelsUsageChartPoint := _ModelsUsageChartPoint{}

	err = json.Unmarshal(data, &varModelsUsageChartPoint)

	if err != nil {
		return err
	}

	*o = ModelsUsageChartPoint(varModelsUsageChartPoint)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cpu")
		delete(additionalProperties, "cpuPrice")
		delete(additionalProperties, "diskGB")
		delete(additionalProperties, "diskPrice")
		delete(additionalProperties, "ramGB")
		delete(additionalProperties, "ramPrice")
		delete(additionalProperties, "time")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModelsUsageChartPoint struct {
	value *ModelsUsageChartPoint
	isSet bool
}

func (v NullableModelsUsageChartPoint) Get() *ModelsUsageChartPoint {
	return v.value
}

func (v *NullableModelsUsageChartPoint) Set(val *ModelsUsageChartPoint) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsUsageChartPoint) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsUsageChartPoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsUsageChartPoint(val *ModelsUsageChartPoint) *NullableModelsUsageChartPoint {
	return &NullableModelsUsageChartPoint{value: val, isSet: true}
}

func (v NullableModelsUsageChartPoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsUsageChartPoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


