# coding: utf-8

"""
    Daytona Analytics API

    Daytona Analytics API - Read-only telemetry and usage data. Authenticated via Daytona API keys or JWT tokens.

    The version of the OpenAPI document: v0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import TypeAdapter
from typing import Optional, Set
from typing_extensions import Self

_JSON_ADAPTER = TypeAdapter(Dict[str, Any])

class ModelsSpan(BaseModel):
    """
    ModelsSpan
    """ # noqa: E501
    duration_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, serialization_alias="durationMs")
    parent_span_id: Optional[StrictStr] = Field(default=None, serialization_alias="parentSpanId")
    span_attributes: Optional[Dict[str, StrictStr]] = Field(default=None, serialization_alias="spanAttributes")
    span_id: Optional[StrictStr] = Field(default=None, serialization_alias="spanId")
    span_name: Optional[StrictStr] = Field(default=None, serialization_alias="spanName")
    status_code: Optional[StrictStr] = Field(default=None, serialization_alias="statusCode")
    status_message: Optional[StrictStr] = Field(default=None, serialization_alias="statusMessage")
    timestamp: Optional[StrictStr] = None
    trace_id: Optional[StrictStr] = Field(default=None, serialization_alias="traceId")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["durationMs", "parentSpanId", "spanAttributes", "spanId", "spanName", "statusCode", "statusMessage", "timestamp", "traceId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return _JSON_ADAPTER.dump_json(self.to_dict()).decode()

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelsSpan from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelsSpan from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "duration_ms": obj.get("durationMs"),
            "parent_span_id": obj.get("parentSpanId"),
            "span_attributes": obj.get("spanAttributes"),
            "span_id": obj.get("spanId"),
            "span_name": obj.get("spanName"),
            "status_code": obj.get("statusCode"),
            "status_message": obj.get("statusMessage"),
            "timestamp": obj.get("timestamp"),
            "trace_id": obj.get("traceId")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


