/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Toolbox API
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface GitPullRequest {
    /**
     * Branch to pull (defaults to the current branch\'s upstream).
     */
    'branch'?: string;
    'password'?: string;
    'path': string;
    /**
     * Remote to pull from (defaults to \"origin\").
     */
    'remote'?: string;
    'username'?: string;
}

