/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Toolbox API
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface KeyboardPressRequest
 */
export interface KeyboardPressRequest {
    /**
     * 
     * @type {string}
     * @memberof KeyboardPressRequest
     */
    'key'?: string;
    /**
     * ctrl, alt, shift, cmd
     * @type {Array<string>}
     * @memberof KeyboardPressRequest
     */
    'modifiers'?: Array<string>;
}

