/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Toolbox API
 * Daytona Toolbox API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProcessStatus
 */
export interface ProcessStatus {
    /**
     * 
     * @type {boolean}
     * @memberof ProcessStatus
     */
    'autoRestart'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProcessStatus
     */
    'pid'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProcessStatus
     */
    'priority'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProcessStatus
     */
    'running'?: boolean;
}

