name: '[PR] SDK Unit Tests'

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  POETRY_VIRTUALENVS_IN_PROJECT: true
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  test-sdk-unit:
    name: SDK Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-toolchain

      - name: Install Python test dependencies
        run: |
          source "$(poetry env info --path)/bin/activate"
          pip install pytest pytest-asyncio

      - name: Publish Java API clients to Maven local
        run: |
          (cd libs/api-client-java && ./gradlew publishToMavenLocal -x test)
          (cd libs/toolbox-api-client-java && ./gradlew publishToMavenLocal -x test)

      - name: Run SDK unit tests
        run: yarn test:unit
