name: daytona workspace-config delete
synopsis: Delete a workspace config
usage: daytona workspace-config delete [flags]
options:
    - name: all
      shorthand: a
      default_value: "false"
      usage: Delete all workspace configs
    - name: force
      shorthand: f
      default_value: "false"
      usage: Force delete prebuild
    - name: "yes"
      shorthand: "y"
      default_value: "false"
      usage: Confirm deletion without prompt
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
see_also:
    - daytona workspace-config - Manage workspace configs
