name: daytona server configure
synopsis: Configure Daytona Server
usage: daytona server configure [flags]
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
see_also:
    - daytona server - Start the server process in daemon mode
