name: daytona project-config delete
synopsis: Delete a project config
usage: daytona project-config delete [flags]
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
    - name: output
      shorthand: o
      usage: Output format. Must be one of (yaml, json)
see_also:
    - daytona project-config - Manage project configs
