name: daytona config
synopsis: Output Daytona configuration
usage: daytona config [flags]
options:
    - name: format
      shorthand: f
      usage: Output format. Must be one of (yaml, json)
    - name: show-api-keys
      shorthand: k
      default_value: "false"
      usage: Show API keys
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
see_also:
    - daytona - Daytona is a Dev Environment Manager
