name: daytona runner config
synopsis: Outputs Daytona Runner config
usage: daytona runner config [flags]
options:
    - name: format
      shorthand: f
      usage: Output format. Must be one of (yaml, json)
    - name: key
      shorthand: k
      default_value: "false"
      usage: Show API Key
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
see_also:
    - daytona runner - Manage the runner
