name: daytona project-config export
synopsis: Export a project config
usage: daytona project-config export [flags]
options:
    - name: all
      shorthand: a
      default_value: "false"
      usage: Export all project configs
    - name: format
      shorthand: f
      usage: Output format. Must be one of (yaml, json)
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
see_also:
    - daytona project-config - Manage project configs
