name: daytona project-config import
synopsis: Import project config from JSON
description: |
    Import project config from a JSON input. Use '-' to read from stdin.
usage: daytona project-config import [-]
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
see_also:
    - daytona project-config - Manage project configs
