name: daytona workspace-config info
synopsis: Show workspace config info
usage: daytona workspace-config info [flags]
options:
    - name: format
      shorthand: f
      usage: Output format. Must be one of (yaml, json)
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
see_also:
    - daytona workspace-config - Manage workspace configs
