name: daytona project-config update
synopsis: Update a project config
usage: daytona project-config update [flags]
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
    - name: output
      shorthand: o
      usage: Output format. Must be one of (yaml, json)
see_also:
    - daytona project-config - Manage project configs
