name: daytona project-config list
synopsis: Lists project configs
usage: daytona project-config list [flags]
options:
    - name: format
      shorthand: f
      usage: Output format. Must be one of (yaml, json)
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
see_also:
    - daytona project-config - Manage project configs
