name: daytona server config
synopsis: Output local Daytona Server config
usage: daytona server config [flags]
options:
    - name: format
      shorthand: f
      usage: Output format. Must be one of (yaml, json)
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
see_also:
    - daytona server - Start the server process in daemon mode
