name: daytona project-config import
synopsis: Import project config from JSON
usage: daytona project-config import [flags]
options:
    - name: file
      shorthand: f
      usage: |
        Import project config from a JSON file. Use '-' to read from stdin.
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
see_also:
    - daytona project-config - Manage project configs
