/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Daytona.ApiClient.Model;
using Daytona.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Daytona.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CreateRunnerResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateRunnerResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateRunnerResponse
        //private CreateRunnerResponse instance;

        public CreateRunnerResponseTests()
        {
            // TODO uncomment below to create an instance of CreateRunnerResponse
            //instance = new CreateRunnerResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateRunnerResponse
        /// </summary>
        [Fact]
        public void CreateRunnerResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateRunnerResponse
            //Assert.IsType<CreateRunnerResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'ApiKey'
        /// </summary>
        [Fact]
        public void ApiKeyTest()
        {
            // TODO unit test for the property 'ApiKey'
        }
    }
}
