/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Daytona.ApiClient.Model;
using Daytona.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Daytona.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing MouseClickResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MouseClickResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MouseClickResponse
        //private MouseClickResponse instance;

        public MouseClickResponseTests()
        {
            // TODO uncomment below to create an instance of MouseClickResponse
            //instance = new MouseClickResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MouseClickResponse
        /// </summary>
        [Fact]
        public void MouseClickResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" MouseClickResponse
            //Assert.IsType<MouseClickResponse>(instance);
        }

        /// <summary>
        /// Test the property 'X'
        /// </summary>
        [Fact]
        public void XTest()
        {
            // TODO unit test for the property 'X'
        }

        /// <summary>
        /// Test the property 'Y'
        /// </summary>
        [Fact]
        public void YTest()
        {
            // TODO unit test for the property 'Y'
        }
    }
}
