/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Daytona.ApiClient.Model;
using Daytona.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Daytona.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PaginatedJobs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaginatedJobsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaginatedJobs
        //private PaginatedJobs instance;

        public PaginatedJobsTests()
        {
            // TODO uncomment below to create an instance of PaginatedJobs
            //instance = new PaginatedJobs();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaginatedJobs
        /// </summary>
        [Fact]
        public void PaginatedJobsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaginatedJobs
            //Assert.IsType<PaginatedJobs>(instance);
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Fact]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }
    }
}
