/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Daytona.ApiClient.Model;
using Daytona.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Daytona.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing SandboxInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SandboxInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SandboxInfo
        //private SandboxInfo instance;

        public SandboxInfoTests()
        {
            // TODO uncomment below to create an instance of SandboxInfo
            //instance = new SandboxInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SandboxInfo
        /// </summary>
        [Fact]
        public void SandboxInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SandboxInfo
            //Assert.IsType<SandboxInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'ProviderMetadata'
        /// </summary>
        [Fact]
        public void ProviderMetadataTest()
        {
            // TODO unit test for the property 'ProviderMetadata'
        }
    }
}
