/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Daytona.ApiClient.Model;
using Daytona.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Daytona.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing StorageAccessDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StorageAccessDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StorageAccessDto
        //private StorageAccessDto instance;

        public StorageAccessDtoTests()
        {
            // TODO uncomment below to create an instance of StorageAccessDto
            //instance = new StorageAccessDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StorageAccessDto
        /// </summary>
        [Fact]
        public void StorageAccessDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" StorageAccessDto
            //Assert.IsType<StorageAccessDto>(instance);
        }

        /// <summary>
        /// Test the property 'AccessKey'
        /// </summary>
        [Fact]
        public void AccessKeyTest()
        {
            // TODO unit test for the property 'AccessKey'
        }

        /// <summary>
        /// Test the property 'Secret'
        /// </summary>
        [Fact]
        public void SecretTest()
        {
            // TODO unit test for the property 'Secret'
        }

        /// <summary>
        /// Test the property 'SessionToken'
        /// </summary>
        [Fact]
        public void SessionTokenTest()
        {
            // TODO unit test for the property 'SessionToken'
        }

        /// <summary>
        /// Test the property 'StorageUrl'
        /// </summary>
        [Fact]
        public void StorageUrlTest()
        {
            // TODO unit test for the property 'StorageUrl'
        }

        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }

        /// <summary>
        /// Test the property 'Bucket'
        /// </summary>
        [Fact]
        public void BucketTest()
        {
            // TODO unit test for the property 'Bucket'
        }
    }
}
