/*
 * Daytona
 *
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Daytona.ApiClient.Model;
using Daytona.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Daytona.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookInitializationStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookInitializationStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookInitializationStatus
        //private WebhookInitializationStatus instance;

        public WebhookInitializationStatusTests()
        {
            // TODO uncomment below to create an instance of WebhookInitializationStatus
            //instance = new WebhookInitializationStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookInitializationStatus
        /// </summary>
        [Fact]
        public void WebhookInitializationStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookInitializationStatus
            //Assert.IsType<WebhookInitializationStatus>(instance);
        }

        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }

        /// <summary>
        /// Test the property 'SvixApplicationId'
        /// </summary>
        [Fact]
        public void SvixApplicationIdTest()
        {
            // TODO unit test for the property 'SvixApplicationId'
        }

        /// <summary>
        /// Test the property 'LastError'
        /// </summary>
        [Fact]
        public void LastErrorTest()
        {
            // TODO unit test for the property 'LastError'
        }

        /// <summary>
        /// Test the property 'RetryCount'
        /// </summary>
        [Fact]
        public void RetryCountTest()
        {
            // TODO unit test for the property 'RetryCount'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
